# Generated by Django 4.2.5 on 2025-03-31 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeronef',
            name='prout',
            field=models.CharField(default='prout', max_length=6),
        ),
    ]
