# Generated by Django 4.2.5 on 2025-03-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0002_aeronef_prout'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='licenceFFPLUM',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
