# Generated by Django 4.2.5 on 2025-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0003_member_licenceffplum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='licenceFFPLUM',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
