# Generated by Django 4.2.5 on 2025-03-31 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_alter_member_licenceffplum'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='LicenceAUV',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='licenceAUVOuiNon', to='intranet.ouinon'),
        ),
        migrations.AlterField(
            model_name='member',
            name='brevetInstructeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='brevetInstructeurOuiNon', to='intranet.ouinon'),
        ),
    ]
