# Generated by Django 4.2.5 on 2025-03-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_member_licenceauv_alter_member_brevetinstructeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='LicenceAUV',
            new_name='licenceAUV',
        ),
        migrations.AddField(
            model_name='member',
            name='dateBaptèmeC2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dateBaptèmeC3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dateBaptèmeC4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dateEmportC2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dateEmportC3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='dateEmportC4',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='datePiloteC2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='datePiloteC3',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='datePiloteC4',
            field=models.DateField(blank=True, null=True),
        ),
    ]
