# Generated by Django 4.2.5 on 2025-03-31 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0006_rename_licenceauv_member_licenceauv_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='dateBaptèmeC2',
            new_name='dateBaptemeC2',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='dateBaptèmeC3',
            new_name='dateBaptemeC3',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='dateBaptèmeC4',
            new_name='dateBaptemeC4',
        ),
    ]
