# Generated by Django 4.2.5 on 2025-04-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0007_rename_datebaptèmec2_member_datebaptemec2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vol',
            old_name='texte',
            new_name='textVVent',
        ),
        migrations.AlterField(
            model_name='budgetligne',
            name='code',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='budgetprojet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='budgetsection',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vol',
            name='instructeur',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
