# Generated by Django 4.2.5 on 2025-04-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0008_rename_texte_vol_textvvent_alter_budgetligne_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='textAltitude',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textAtterrissage',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textDecollage',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textNav',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textRadio',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textStress',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textTdp',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textVol',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AlterField(
            model_name='vol',
            name='textVVent',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
    ]
