# Generated by Django 4.2.5 on 2025-04-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0009_vol_textaltitude_vol_textatterrissage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vol',
            name='textBaseULM',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
        migrations.AddField(
            model_name='vol',
            name='textCommentaire',
            field=models.CharField(blank=True, default='RAS', max_length=1000),
        ),
    ]
