# Generated by Django 4.2.5 on 2025-04-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0010_vol_textbaseulm_vol_textcommentaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEpargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('produit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
            ],
        ),
    ]
