# Generated by Django 4.2.5 on 2025-04-10 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Intranet', '0011_compteepargne'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompteEpargneOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='CE-XXXX', max_length=9)),
                ('charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('produit', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('compteEpargne', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Intranet.compteepargne')),
            ],
            options={
                'ordering': ['-date', 'code'],
            },
        ),
    ]
