# Generated by Django 4.2.5 on 2025-04-18 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0012_compteepargneoperation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='AUV_20XX_XXXX', max_length=13)),
                ('objet', models.CharField(max_length=100)),
                ('clientName', models.CharField(max_length=50)),
                ('clientVorname', models.CharField(max_length=50)),
                ('clientZip', models.CharField(max_length=5)),
                ('clientCity', models.CharField(max_length=50)),
                ('clientAdress', models.CharField(max_length=200)),
                ('clientCountry', models.CharField(default='FRANCE', max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='budgetligne',
            name='projet',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.budgetprojet'),
        ),
        migrations.AlterField(
            model_name='budgetoperation',
            name='budget',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='intranet.budgetbudget'),
        ),
        migrations.AlterField(
            model_name='budgetoperation',
            name='code',
            field=models.CharField(default='PXX-0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='budgetprojet',
            name='section',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.budgetsection'),
        ),
        migrations.AlterField(
            model_name='compteepargneoperation',
            name='code',
            field=models.CharField(default='CE-0000', max_length=9),
        ),
        migrations.CreateModel(
            name='OperationFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='PXXXX-XXXX', max_length=10)),
                ('objet', models.CharField(max_length=150)),
                ('prixHT', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('nb', models.IntegerField(default=1)),
                ('codeLigne', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='intranet.budgetoperation')),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.facture')),
            ],
        ),
    ]
