# Generated by Django 4.2.5 on 2025-04-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_facture_alter_budgetligne_projet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='objet',
        ),
        migrations.AddField(
            model_name='facture',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
