# Generated by Django 4.2.5 on 2025-04-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0014_remove_facture_objet_facture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='code',
            field=models.CharField(default='AUV-2025-0000', max_length=13),
        ),
    ]
