# Generated by Django 4.2.5 on 2025-04-18 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_alter_facture_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date', 'code']},
        ),
        migrations.AddField(
            model_name='operationfacture',
            name='acquite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acquiteOuiNon', to='intranet.ouinon'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='clientVorname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
