# Generated by Django 4.2.5 on 2025-04-18 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_alter_facture_options_operationfacture_acquite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationfacture',
            name='acquite',
        ),
        migrations.AddField(
            model_name='facture',
            name='acquite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acquiteOuiNon', to='intranet.ouinon'),
        ),
    ]
