# Generated by Django 4.2.5 on 2025-04-21 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_remove_operationfacture_acquite_facture_acquite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationfacture',
            name='codeLigne',
        ),
        migrations.AddField(
            model_name='operationfacture',
            name='ligne',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='intranet.budgetligne'),
        ),
        migrations.AlterField(
            model_name='budgetoperation',
            name='code',
            field=models.CharField(default='PXXXX-0000', max_length=10),
        ),
    ]
